import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useAppContext } from '../context';
import type { AgentProfile, EvaluationCampaign } from '../adapters/interfaces';

const digest = async (value: string) => { const bytes = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value)); return `sha256:${Array.from(new Uint8Array(bytes)).map((b) => b.toString(16).padStart(2, '0')).join('')}`; };
export function Evaluations() {
  const { account, agentApi, evaluationApi } = useAppContext(); const [agents, setAgents] = useState<AgentProfile[]>([]); const [campaigns, setCampaigns] = useState<EvaluationCampaign[]>([]); const [name, setName] = useState(''); const [agentId, setAgentId] = useState(''); const [objective, setObjective] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (!account || !agentApi || !evaluationApi) return; Promise.all([agentApi.listOwnedAgents(), evaluationApi.listCampaigns()]).then(([a, c]) => { setAgents(a); setCampaigns(c); if (a[0]) setAgentId((current) => current || a[0].agentId); }).catch((e) => setError(e instanceof Error ? e.message : 'Could not load evaluations.')); }, [account, agentApi, evaluationApi]);
  async function create() { const agent = agents.find((a) => a.agentId === agentId); if (!agent || !name.trim() || !objective.trim() || !evaluationApi) return; setBusy(true); setError(''); try { const packId = await digest(`pack|${name}|${objective}`); const campaignId = await digest(`campaign|${packId}|${Date.now()}`); const scenarioId = `scenario-${(await digest(objective)).slice(-12)}`; await evaluationApi.createPack({ packId, version: '1.0.0', name, scenarios: [{ schema: 'arena-test-scenario-v1', scenarioId, version: '1.0.0', level: 'RESPONSE', objective, context: '', constraints: [], availableActions: [], forbiddenActionIds: [], confirmationRequiredActionIds: [], maxProposedActions: 0 }] }); const campaign = await evaluationApi.createSoloCampaign({ campaignId, agentId: agent.agentId, agentsVersion: agent.agentsVersion, packId, packVersion: '1.0.0', runtimePolicy: { model: 'configured', maxOutputTokens: 2048, temperature: 0, maxProviderAttempts: 2 } }); setCampaigns((items) => [campaign, ...items]); setName(''); setObjective(''); } catch (e) { setError(e instanceof Error ? e.message : 'Could not create evaluation.'); } finally { setBusy(false); } }
  if (!account) return <section className="mx-auto max-w-5xl"><h1 className="page-title">Evaluations</h1><div className="glass-panel mt-8 p-7">Connect a wallet to create and inspect SOLO evaluations.</div></section>;
  return <section className="mx-auto max-w-5xl space-y-8"><div><p className="page-kicker">Arena ISS / SOLO</p><h1 className="page-title">Evaluations</h1><p className="page-lede">Run a versioned Agent against an immutable Test Pack.</p></div><div className="glass-panel p-6 md:p-8"><h2 className="text-xl font-bold">Create SOLO evaluation</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><label>Evaluation name<input className="field-control mt-2" value={name} onChange={(e) => setName(e.target.value)} /></label><label>Agent<select className="field-control mt-2" value={agentId} onChange={(e) => setAgentId(e.target.value)}>{agents.map((a) => <option key={a.agentId} value={a.agentId}>{a.name}</option>)}</select></label><label className="md:col-span-2">Scenario objective<textarea className="field-control mt-2 min-h-28" value={objective} onChange={(e) => setObjective(e.target.value)} placeholder="What should the Agent accomplish?" /></label></div>{error && <p role="alert" className="mt-4 text-red-900">{error}</p>}<button className="metal-button-solid mt-5" disabled={busy || !agentId || !name.trim() || !objective.trim()} onClick={create}>{busy ? 'Creating…' : 'Create evaluation'}</button></div><div><h2 className="mb-4 text-xl font-bold">My campaigns</h2>{campaigns.length === 0 ? <div className="glass-panel p-7 text-neutral-700">No evaluations yet.</div> : <ul className="space-y-3">{campaigns.map((c) => <li key={c.campaignId} className="glass-panel flex flex-wrap items-center justify-between gap-4 p-5"><div><p className="font-mono text-xs">{c.campaignId}</p><p className="mt-2 font-semibold">{c.packVersion} · {c.items.length} scenario{c.items.length === 1 ? '' : 's'}</p></div><Link className="metal-button-ghost" to={`/evaluations/${c.campaignId}`}>{c.state} →</Link></li>)}</ul>}</div></section>;
}
