import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useAppContext } from '../context';
import type { EvaluationCampaign, EvaluationRun } from '../adapters/interfaces';
export function EvaluationDetail() { const { id } = useParams<{ id: string }>(); const { evaluationApi } = useAppContext(); const [campaign, setCampaign] = useState<EvaluationCampaign | null>(null); const [runs, setRuns] = useState<EvaluationRun[]>([]); const [error, setError] = useState('');
  useEffect(() => { if (!id || !evaluationApi) return; Promise.all([evaluationApi.getCampaign(id), evaluationApi.listRuns()]).then(([c, all]) => { setCampaign(c); setRuns(all.filter((r) => c?.items.some((i) => i.runIds.includes(r.runId)))); }).catch((e) => setError(e instanceof Error ? e.message : 'Could not load evaluation.')); }, [id, evaluationApi]);
  if (error) return <div role="alert" className="glass-panel mx-auto max-w-4xl p-8">{error}</div>; if (!campaign) return <div role="status" className="glass-panel mx-auto max-w-4xl p-8">Loading evaluation…</div>;
  return <section className="mx-auto max-w-4xl space-y-8"><Link to="/evaluations" className="text-sm underline">← All evaluations</Link><div><p className="page-kicker">SOLO campaign</p><h1 className="page-title">Run Detail</h1><p className="mt-3 font-mono text-xs break-all">{campaign.campaignId}</p></div><div className="glass-panel p-6"><div className="grid gap-3 sm:grid-cols-3"><Fact label="State" value={campaign.state}/><Fact label="Pack" value={`${campaign.packId} · ${campaign.packVersion}`}/><Fact label="Agent version" value={campaign.agentVersionId}/></div></div><div className="space-y-3"><h2 className="text-xl font-bold">Scenario runs</h2>{campaign.items.map((item) => <div key={item.scenarioId} className="glass-panel p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">{item.scenarioId}</p><p className="text-sm text-neutral-600">{item.state} · attempt {item.attempt}</p></div>{item.score && <span className="retro-chip px-3 py-2">{item.score} {item.overallScore !== undefined ? `· ${item.overallScore}/100` : ''}</span>}</div><div className="mt-4 space-y-2">{item.runIds.map((runId) => <Link className="block font-mono text-xs underline" key={runId} to={`/evaluation-runs/${runId}`}>{runId}</Link>)}</div></div>)}</div>{runs.length > 0 && <p className="text-xs text-neutral-600">{runs.length} run record{runs.length === 1 ? '' : 's'} available. Public detail omits private prompt and provider bytes.</p>}</section>; }
function Fact({ label, value }: { label: string; value: string }) { return <div className="retro-inset p-3"><p className="text-[10px] uppercase tracking-wider">{label}</p><p className="mt-1 break-all font-mono text-xs">{value}</p></div>; }
