import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { useAppContext } from '../context';
import type { MarketplaceCertificate, MarketplaceListing } from '../adapters/interfaces';

const uuid = () => crypto.randomUUID();
const nowSeconds = () => Math.floor(Date.now() / 1000);
export function Marketplace() {
  const { account, marketplaceApi, agentApi } = useAppContext();
  const [listings, setListings] = useState<MarketplaceListing[]>([]); const [certificates, setCertificates] = useState<MarketplaceCertificate[]>([]); const [agents, setAgents] = useState<any[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  const [eligibility, setEligibility] = useState({ agentId: '', agentsVersion: '', campaignIds: '', expiresAt: String(nowSeconds() + 30 * 86400), judgeAddress: '' });
  const [listing, setListing] = useState({ certificateDigest: '', price: '', expiresAt: String(nowSeconds() + 7 * 86400) });
  const refresh = async () => { if (!marketplaceApi) return; const [next, owned] = await Promise.all([marketplaceApi.listListings(), account ? marketplaceApi.listCertificates() : Promise.resolve([])]); setListings(next); setCertificates(owned); if (agentApi) setAgents(await agentApi.listOwnedAgents()); };
  useEffect(() => { refresh().catch((e) => setError(e.message)); }, [marketplaceApi, account]);
  const selectedCertificate = useMemo(() => certificates.find((row) => row.certificateDigest === listing.certificateDigest), [certificates, listing.certificateDigest]);
  async function issueEligibility(event: React.FormEvent) { event.preventDefault(); if (!marketplaceApi) return; setBusy('eligibility'); setError(''); try { const agent = agents.find((row) => row.agentId === eligibility.agentId); await marketplaceApi.createEligibility({ agentId: eligibility.agentId, agentsVersion: eligibility.agentsVersion || agent?.agentsVersion, campaignIds: eligibility.campaignIds.split(',').map((x) => x.trim()).filter(Boolean), issuedAt: nowSeconds(), expiresAt: Number(eligibility.expiresAt), network: 'studio-next', chainId: 61997, judgeAddress: eligibility.judgeAddress }); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Eligibility failed'); } finally { setBusy(''); } }
  async function createListing(event: React.FormEvent) { event.preventDefault(); if (!marketplaceApi || !selectedCertificate) return; setBusy('listing'); setError(''); try { await marketplaceApi.createListing({ listingId: String(Date.now()), certificateDigest: selectedCertificate.certificateDigest, agentId: selectedCertificate.agentId, agentsVersion: selectedCertificate.agentVersionId, agentsCommitment: selectedCertificate.agentsCommitment, price: listing.price, expiresAt: Number(listing.expiresAt), idempotencyKey: uuid() }); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Listing failed'); } finally { setBusy(''); } }
  async function buy(row: MarketplaceListing) { if (!marketplaceApi) return; setBusy(`buy-${row.listingId}`); setError(''); try { await marketplaceApi.buy(row.listingId, uuid(), uuid()); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Purchase failed'); } finally { setBusy(''); } }
  return <section aria-labelledby="marketplace-heading" className="mx-auto max-w-6xl">
    <p className="page-kicker">Agent Exchange · Arc Testnet</p><div className="flex flex-wrap items-end justify-between gap-6"><div><h1 id="marketplace-heading" className="page-title">Marketplace</h1><p className="page-lede">Buy exact Evo-passed Agent versions. Every sale settles in USDC with a fixed 1% platform fee.</p></div><span className="retro-chip px-3 py-2 text-xs">Arc · 1% fee</span></div>
    {error && <div role="alert" className="mt-8 border border-red-700 bg-red-50 p-4 text-sm">{error}</div>}
    <div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{listings.map((row) => <article className="glass-panel flex min-h-64 flex-col p-5" key={row.listingId}><div className="flex items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-widest text-neutral-600">Listing #{row.listingId}</p><h2 className="mt-2 text-2xl font-bold">{row.name}</h2></div><span className="retro-chip px-2 py-1 text-xs">{row.state}</span></div><dl className="mt-8 space-y-3 text-sm"><div className="flex justify-between gap-3"><dt className="text-neutral-600">Price</dt><dd className="font-mono font-bold">{row.price} USDC</dd></div><div className="flex justify-between gap-3"><dt className="text-neutral-600">Version</dt><dd className="max-w-[14rem] truncate font-mono">{row.agentVersionId}</dd></div></dl><div className="mt-auto pt-6">{row.state === 'ACTIVE' && account ? <button className="metal-button-solid w-full" disabled={busy !== ''} onClick={() => buy(row)}>{busy === `buy-${row.listingId}` ? 'Submitting…' : 'Buy with managed wallet'}</button> : <p className="text-xs text-neutral-600">{row.state === 'ACTIVE' ? 'Sign in to purchase.' : 'Awaiting Arc confirmation.'}</p>}</div></article>)}</div>
    {account && <div className="mt-14 grid gap-6 lg:grid-cols-2"><form className="glass-panel p-6" onSubmit={issueEligibility}><h2 className="text-xl font-bold">Certify an Evo version</h2><p className="mt-2 text-sm text-neutral-600">Two finalized campaigns are checked server-side against the locked six-scenario policy.</p><label className="mt-5 block text-sm font-semibold">Agent<input className="field-control mt-2" list="marketplace-agents" value={eligibility.agentId} onChange={(e) => setEligibility({ ...eligibility, agentId: e.target.value })} required /></label><datalist id="marketplace-agents">{agents.map((agent) => <option value={agent.agentId} key={agent.agentId}>{agent.name}</option>)}</datalist><label className="mt-4 block text-sm font-semibold">Version digest<input className="field-control mt-2" value={eligibility.agentsVersion} onChange={(e) => setEligibility({ ...eligibility, agentsVersion: e.target.value })} required /></label><label className="mt-4 block text-sm font-semibold">Two campaign IDs<input className="field-control mt-2" placeholder="sha256:…, sha256:…" value={eligibility.campaignIds} onChange={(e) => setEligibility({ ...eligibility, campaignIds: e.target.value })} required /></label><label className="mt-4 block text-sm font-semibold">GenLayer judge address<input className="field-control mt-2" value={eligibility.judgeAddress} onChange={(e) => setEligibility({ ...eligibility, judgeAddress: e.target.value })} required /></label><button className="metal-button-solid mt-6" disabled={busy !== ''}>{busy === 'eligibility' ? 'Checking…' : 'Run eligibility check'}</button></form><form className="glass-panel p-6" onSubmit={createListing}><h2 className="text-xl font-bold">List an approved version</h2><p className="mt-2 text-sm text-neutral-600">Listing executes on Arc; private AGENTS.md stays server-side until canonical sale delivery.</p><label className="mt-5 block text-sm font-semibold">Approved certificate<select className="field-control mt-2" value={listing.certificateDigest} onChange={(e) => setListing({ ...listing, certificateDigest: e.target.value })} required><option value="">Select certificate</option>{certificates.filter((c) => c.state === 'APPROVED').map((c) => <option value={c.certificateDigest} key={c.certificateDigest}>{c.certificateDigest.slice(0, 20)}… · {c.overallScore}/100</option>)}</select></label><label className="mt-4 block text-sm font-semibold">Price in USDC base units<input className="field-control mt-2" inputMode="numeric" pattern="[1-9][0-9]*" value={listing.price} onChange={(e) => setListing({ ...listing, price: e.target.value })} required /></label><button className="metal-button-solid mt-6" disabled={busy !== '' || !selectedCertificate}>{busy === 'listing' ? 'Submitting…' : 'List on Arc'}</button></form></div>}
    {!account && <p className="mt-10 text-sm text-neutral-600">Sign in to certify or list an Agent. <Link to="/agents" className="font-semibold underline">Manage Agents</Link>.</p>}
  </section>;
}
